<?php

namespace Database\Seeders;

use App\Models\Thana;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ThanaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $thana = [
            ['district_id' => 1, 'name' => 'Adamdighi'],
            ['district_id' => 1, 'name' => 'Bogura Sadar'],
            ['district_id' => 1, 'name' => 'Dhunat'],
            ['district_id' => 1, 'name' => 'Dhupchanchia'],
            ['district_id' => 1, 'name' => 'Gabtali'],
            ['district_id' => 1, 'name' => 'Kahaloo'],
            ['district_id' => 1, 'name' => 'Nandigram'],
            ['district_id' => 1, 'name' => 'Sariakandi'],
            ['district_id' => 1, 'name' => 'Shajahanpur'],
            ['district_id' => 1, 'name' => 'Sherpur'],
            ['district_id' => 1, 'name' => 'Shibganj'],
            ['district_id' => 1, 'name' => 'Sonatola'],
            ['district_id' => 2, 'name' => 'Bholahat'],
            ['district_id' => 2, 'name' => 'Gomastapur'],
            ['district_id' => 2, 'name' => 'Nachole'],
            ['district_id' => 2, 'name' => 'Nawabganj Sadar'],
            ['district_id' => 2, 'name' => 'Shibganj'],
            ['district_id' => 3, 'name' => 'Akkelpur'],
            ['district_id' => 3, 'name' => 'Joypurhat Sadar'],
            ['district_id' => 3, 'name' => 'Kalai'],
            ['district_id' => 3, 'name' => 'Khetlal'],
            ['district_id' => 3, 'name' => 'Panchbibi'],
            ['district_id' => 4, 'name' => 'Atrai'],
            ['district_id' => 4, 'name' => 'Badalgachhi'],
            ['district_id' => 4, 'name' => 'Manda'],
            ['district_id' => 4, 'name' => 'Dhamoirhat'],
            ['district_id' => 4, 'name' => 'Mohadevpur'],
            ['district_id' => 4, 'name' => 'Naogaon Sadar'],
            ['district_id' => 4, 'name' => 'Niamatpur'],
            ['district_id' => 4, 'name' => 'Patnitala'],
            ['district_id' => 4, 'name' => 'Porsha'],
            ['district_id' => 4, 'name' => 'Raninagar'],
            ['district_id' => 4, 'name' => 'Sapahar'],
            ['district_id' => 5, 'name' => 'Bagatipara'],
            ['district_id' => 5, 'name' => 'Baraigram'],
            ['district_id' => 5, 'name' => 'Gurudaspur'],
            ['district_id' => 5, 'name' => 'Lalpur'],
            ['district_id' => 5, 'name' => 'Natore Sadar'],
            ['district_id' => 5, 'name' => 'Singra'],
            ['district_id' => 5, 'name' => 'Naldanga'],
            ['district_id' => 6, 'name' => 'Atgharia'],
            ['district_id' => 6, 'name' => 'Bera'],
            ['district_id' => 6, 'name' => 'Bhangura'],
            ['district_id' => 6, 'name' => 'Chatmohar'],
            ['district_id' => 6, 'name' => 'Faridpur'],
            ['district_id' => 6, 'name' => 'Ishwardi'],
            ['district_id' => 6, 'name' => 'Pabna Sadar'],
            ['district_id' => 6, 'name' => 'Santhia'],
            ['district_id' => 6, 'name' => 'Sujanagar'],
            ['district_id' => 7, 'name' => 'Bagha'],
            ['district_id' => 7, 'name' => 'Bagmara'],
            ['district_id' => 7, 'name' => 'Charghat'],
            ['district_id' => 7, 'name' => 'Durgapur'],
            ['district_id' => 7, 'name' => 'Godagari'],
            ['district_id' => 7, 'name' => 'Mohanpur'],
            ['district_id' => 7, 'name' => 'Paba'],
            ['district_id' => 7, 'name' => 'Puthia'],
            ['district_id' => 7, 'name' => 'Tanore'],
            ['district_id' => 8, 'name' => 'Belkuchi'],
            ['district_id' => 8, 'name' => 'Chauhali'],
            ['district_id' => 8, 'name' => 'Kamarkhanda'],
            ['district_id' => 8, 'name' => 'Kazipur'],
            ['district_id' => 8, 'name' => 'Raiganj'],
            ['district_id' => 8, 'name' => 'Shahjadpur'],
            ['district_id' => 8, 'name' => 'Sirajganj Sadar'],
            ['district_id' => 8, 'name' => 'Tarash'],
            ['district_id' => 8, 'name' => 'Ullahpara'],
            ['district_id' => 9, 'name' => 'Birampur'],
            ['district_id' => 9, 'name' => 'Birganj'],
            ['district_id' => 9, 'name' => 'Biral'],
            ['district_id' => 9, 'name' => 'Bochaganj'],
            ['district_id' => 9, 'name' => 'Chirirbandar'],
            ['district_id' => 9, 'name' => 'Phulbari'],
            ['district_id' => 9, 'name' => 'Ghoraghat'],
            ['district_id' => 9, 'name' => 'Hakimpur'],
            ['district_id' => 9, 'name' => 'Kaharole'],
            ['district_id' => 9, 'name' => 'Khansama'],
            ['district_id' => 9, 'name' => 'Dinajpur Sadar'],
            ['district_id' => 9, 'name' => 'Nawabganj'],
            ['district_id' => 9, 'name' => 'Parbatipur'],
            ['district_id' => 10, 'name' => 'Phulchhari'],
            ['district_id' => 10, 'name' => 'Gaibandha Sadar'],
            ['district_id' => 10, 'name' => 'Gobindaganj'],
            ['district_id' => 10, 'name' => 'Palashbari'],
            ['district_id' => 10, 'name' => 'Sadullapur'],
            ['district_id' => 10, 'name' => 'Sughatta'],
            ['district_id' => 10, 'name' => 'Sundarganj'],
            ['district_id' => 11, 'name' => 'Bhurungamari'],
            ['district_id' => 11, 'name' => 'Char Rajibpur'],
            ['district_id' => 11, 'name' => 'Chilmari'],
            ['district_id' => 11, 'name' => 'Phulbari'],
            ['district_id' => 11, 'name' => 'Kurigram Sadar'],
            ['district_id' => 11, 'name' => 'Nageshwari'],
            ['district_id' => 11, 'name' => 'Rajarhat'],
            ['district_id' => 11, 'name' => 'Raomari'],
            ['district_id' => 11, 'name' => 'Ulipur'],
            ['district_id' => 12, 'name' => 'Aditmari'],
            ['district_id' => 12, 'name' => 'Hatibandha'],
            ['district_id' => 12, 'name' => 'Kaliganj'],
            ['district_id' => 12, 'name' => 'Lalmonirhat Sadar'],
            ['district_id' => 12, 'name' => 'Patgram'],
            ['district_id' => 13, 'name' => 'Dimla'],
            ['district_id' => 13, 'name' => 'Domar'],
            ['district_id' => 13, 'name' => 'Jaldhaka'],
            ['district_id' => 13, 'name' => 'Kishoreganj'],
            ['district_id' => 13, 'name' => 'Nilphamari Sadar'],
            ['district_id' => 13, 'name' => 'Saidpur'],
            ['district_id' => 14, 'name' => 'Atwari'],
            ['district_id' => 14, 'name' => 'Boda'],
            ['district_id' => 14, 'name' => 'Debiganj'],
            ['district_id' => 14, 'name' => 'Panchagarh Sadar'],
            ['district_id' => 14, 'name' => 'Tetulia'],
            ['district_id' => 15, 'name' => 'Badarganj'],
            ['district_id' => 15, 'name' => 'Gangachhara'],
            ['district_id' => 15, 'name' => 'Kaunia'],
            ['district_id' => 15, 'name' => 'Rangpur Sadar'],
            ['district_id' => 15, 'name' => 'Mithapukur'],
            ['district_id' => 15, 'name' => 'Pirgachha'],
            ['district_id' => 15, 'name' => 'Pirganj'],
            ['district_id' => 15, 'name' => 'Taraganj'],
            ['district_id' => 16, 'name' => 'Baliadangi'],
            ['district_id' => 16, 'name' => 'Haripur'],
            ['district_id' => 16, 'name' => 'Pirganj'],
            ['district_id' => 16, 'name' => 'Ranisankail'],
            ['district_id' => 16, 'name' => 'Thakurgaon Sadar'],
            ['district_id' => 17, 'name' => 'Baksiganj'],
            ['district_id' => 17, 'name' => 'Dewanganj'],
            ['district_id' => 17, 'name' => 'Islampur'],
            ['district_id' => 17, 'name' => 'Jamalpur Sadar'],
            ['district_id' => 17, 'name' => 'Madarganj'],
            ['district_id' => 17, 'name' => 'Melandaha'],
            ['district_id' => 17, 'name' => 'Sarishabari'],
            ['district_id' => 18, 'name' => 'Trishal'],
            ['district_id' => 18, 'name' => 'Dhobaura'],
            ['district_id' => 18, 'name' => 'Fulbaria'],
            ['district_id' => 18, 'name' => 'Gafargaon'],
            ['district_id' => 18, 'name' => 'Gauripur'],
            ['district_id' => 18, 'name' => 'Haluaghat'],
            ['district_id' => 18, 'name' => 'Ishwarganj'],
            ['district_id' => 18, 'name' => 'Mymensingh Sadar'],
            ['district_id' => 18, 'name' => 'Muktagachha'],
            ['district_id' => 18, 'name' => 'Nandail'],
            ['district_id' => 18, 'name' => 'Phulpur'],
            ['district_id' => 18, 'name' => 'Bhaluka'],
            ['district_id' => 18, 'name' => 'Tara Khanda'],
            ['district_id' => 19, 'name' => 'Atpara'],
            ['district_id' => 19, 'name' => 'Barhatta'],
            ['district_id' => 19, 'name' => 'Durgapur'],
            ['district_id' => 19, 'name' => 'Khaliajuri'],
            ['district_id' => 19, 'name' => 'Kalmakanda'],
            ['district_id' => 19, 'name' => 'Kendua'],
            ['district_id' => 19, 'name' => 'Madan'],
            ['district_id' => 19, 'name' => 'Mohanganj'],
            ['district_id' => 19, 'name' => 'Netrokona Sadar'],
            ['district_id' => 19, 'name' => 'Purbadhala'],
            ['district_id' => 20, 'name' => 'Jhenaigati'],
            ['district_id' => 20, 'name' => 'Nakla'],
            ['district_id' => 20, 'name' => 'Nalitabari'],
            ['district_id' => 20, 'name' => 'Sherpur Sadar'],
            ['district_id' => 20, 'name' => 'Sreebardi'],
            ['district_id' => 21, 'name' => 'Amtali'],
            ['district_id' => 21, 'name' => 'Bamna'],
            ['district_id' => 21, 'name' => 'Barguna Sadar'],
            ['district_id' => 21, 'name' => 'Betagi'],
            ['district_id' => 21, 'name' => 'Patharghata'],
            ['district_id' => 21, 'name' => 'Taltali'],
            ['district_id' => 22, 'name' => 'Agailjhara'],
            ['district_id' => 22, 'name' => 'Babuganj'],
            ['district_id' => 22, 'name' => 'Bakerganj'],
            ['district_id' => 22, 'name' => 'Banaripara'],
            ['district_id' => 22, 'name' => 'Gaurnadi'],
            ['district_id' => 22, 'name' => 'Hizla'],
            ['district_id' => 22, 'name' => 'Barishal Sadar'],
            ['district_id' => 22, 'name' => 'Mehendiganj'],
            ['district_id' => 22, 'name' => 'Muladi'],
            ['district_id' => 22, 'name' => 'Wazirpur'],
            ['district_id' => 23, 'name' => 'Bhola Sadar'],
            ['district_id' => 23, 'name' => 'Burhanuddin'],
            ['district_id' => 23, 'name' => 'Char Fasson'],
            ['district_id' => 23, 'name' => 'Daulatkhan'],
            ['district_id' => 23, 'name' => 'Lalmohan'],
            ['district_id' => 23, 'name' => 'Manpura'],
            ['district_id' => 23, 'name' => 'Tazumuddin'],
            ['district_id' => 24, 'name' => 'Jhalokati Sadar'],
            ['district_id' => 24, 'name' => 'Kathalia'],
            ['district_id' => 24, 'name' => 'Nalchity'],
            ['district_id' => 24, 'name' => 'Rajapur'],
            ['district_id' => 25, 'name' => 'Bauphal'],
            ['district_id' => 25, 'name' => 'Dashmina'],
            ['district_id' => 25, 'name' => 'Galachipa'],
            ['district_id' => 25, 'name' => 'Kalapara'],
            ['district_id' => 25, 'name' => 'Mirzaganj'],
            ['district_id' => 25, 'name' => 'Patuakhali Sadar'],
            ['district_id' => 25, 'name' => 'Rangabali'],
            ['district_id' => 25, 'name' => 'Dumki'],
            ['district_id' => 26, 'name' => 'Bhandaria'],
            ['district_id' => 26, 'name' => 'Kawkhali'],
            ['district_id' => 26, 'name' => 'Mathbaria'],
            ['district_id' => 26, 'name' => 'Nazirpur'],
            ['district_id' => 26, 'name' => 'Pirojpur Sadar'],
            ['district_id' => 26, 'name' => 'Nesarabad (Swarupkati)'],
            ['district_id' => 26, 'name' => 'Indurkani'],
            ['district_id' => 27, 'name' => 'Ali Kadam'],
            ['district_id' => 27, 'name' => 'Bandarban Sadar'],
            ['district_id' => 27, 'name' => 'Lama'],
            ['district_id' => 27, 'name' => 'Naikhongchhari'],
            ['district_id' => 27, 'name' => 'Rowangchhari'],
            ['district_id' => 27, 'name' => 'Ruma'],
            ['district_id' => 27, 'name' => 'Thanchi'],
            ['district_id' => 28, 'name' => 'Akhaura'],
            ['district_id' => 28, 'name' => 'Bancharampur'],
            ['district_id' => 28, 'name' => 'Brahmanbaria Sadar'],
            ['district_id' => 28, 'name' => 'Kasba'],
            ['district_id' => 28, 'name' => 'Nabinagar'],
            ['district_id' => 28, 'name' => 'Nasirnagar'],
            ['district_id' => 28, 'name' => 'Sarail'],
            ['district_id' => 28, 'name' => 'Ashuganj'],
            ['district_id' => 28, 'name' => 'Bijoynagar'],
            ['district_id' => 29, 'name' => 'Chandpur Sadar'],
            ['district_id' => 29, 'name' => 'Faridganj'],
            ['district_id' => 29, 'name' => 'Haimchar'],
            ['district_id' => 29, 'name' => 'Haziganj'],
            ['district_id' => 29, 'name' => 'Kachua'],
            ['district_id' => 29, 'name' => 'Matlab Dakshin'],
            ['district_id' => 29, 'name' => 'Matlab Uttar'],
            ['district_id' => 29, 'name' => 'Shahrasti'],
            ['district_id' => 30, 'name' => 'Anwara'],
            ['district_id' => 30, 'name' => 'Banshkhali'],
            ['district_id' => 30, 'name' => 'Boalkhali'],
            ['district_id' => 30, 'name' => 'Chandanaish'],
            ['district_id' => 30, 'name' => 'Fatikchhari'],
            ['district_id' => 30, 'name' => 'Hathazari'],
            ['district_id' => 30, 'name' => 'Karnaphuli'],
            ['district_id' => 30, 'name' => 'Lohagara'],
            ['district_id' => 30, 'name' => 'Mirsharai'],
            ['district_id' => 30, 'name' => 'Patiya'],
            ['district_id' => 30, 'name' => 'Rangunia'],
            ['district_id' => 30, 'name' => 'Raozan'],
            ['district_id' => 30, 'name' => 'Sandwip'],
            ['district_id' => 30, 'name' => 'Satkania'],
            ['district_id' => 30, 'name' => 'Sitakunda'],
            ['district_id' => 31, 'name' => 'Barura'],
            ['district_id' => 31, 'name' => 'Brahmanpara'],
            ['district_id' => 31, 'name' => 'Burichang'],
            ['district_id' => 31, 'name' => 'Chandina'],
            ['district_id' => 31, 'name' => 'Chauddagram'],
            ['district_id' => 31, 'name' => 'Daudkandi'],
            ['district_id' => 31, 'name' => 'Debidwar'],
            ['district_id' => 31, 'name' => 'Homna'],
            ['district_id' => 31, 'name' => 'Laksam'],
            ['district_id' => 31, 'name' => 'Lalmai'],
            ['district_id' => 31, 'name' => 'Muradnagar'],
            ['district_id' => 31, 'name' => 'Nangalkot'],
            ['district_id' => 31, 'name' => 'Cumilla Adarsha Sadar'],
            ['district_id' => 31, 'name' => 'Meghna'],
            ['district_id' => 31, 'name' => 'Titas'],
            ['district_id' => 31, 'name' => 'Monohargonj'],
            ['district_id' => 31, 'name' => 'Cumilla Sadar Dakshin'],
            ['district_id' => 32, 'name' => 'Chakaria'],
            ['district_id' => 32, 'name' => "Cox's Bazar Sadar"],
            ['district_id' => 32, 'name' => 'Kutubdia'],
            ['district_id' => 32, 'name' => 'Maheshkhali'],
            ['district_id' => 32, 'name' => 'Ramu'],
            ['district_id' => 32, 'name' => 'Teknaf'],
            ['district_id' => 32, 'name' => 'Ukhia'],
            ['district_id' => 32, 'name' => 'Pekua'],
            ['district_id' => 32, 'name' => 'Eidgaon'],
            ['district_id' => 33, 'name' => 'Chhagalnaiya'],
            ['district_id' => 33, 'name' => 'Daganbhuiyan'],
            ['district_id' => 33, 'name' => 'Feni Sadar'],
            ['district_id' => 33, 'name' => 'Parshuram'],
            ['district_id' => 33, 'name' => 'Sonagazi'],
            ['district_id' => 33, 'name' => 'Fulgazi'],
            ['district_id' => 34, 'name' => 'Dighinala'],
            ['district_id' => 34, 'name' => 'Khagrachhari'],
            ['district_id' => 34, 'name' => 'Lakshmichhari'],
            ['district_id' => 34, 'name' => 'Mahalchhari'],
            ['district_id' => 34, 'name' => 'Manikchhari'],
            ['district_id' => 34, 'name' => 'Matiranga'],
            ['district_id' => 34, 'name' => 'Panchhari'],
            ['district_id' => 34, 'name' => 'Ramgarh'],
            ['district_id' => 34, 'name' => 'Guimara'],
            ['district_id' => 35, 'name' => 'Lakshmipur Sadar'],
            ['district_id' => 35, 'name' => 'Raipur'],
            ['district_id' => 35, 'name' => 'Ramganj'],
            ['district_id' => 35, 'name' => 'Ramgati'],
            ['district_id' => 35, 'name' => 'Kamalnagar'],
            ['district_id' => 36, 'name' => 'Begumganj'],
            ['district_id' => 36, 'name' => 'Noakhali Sadar'],
            ['district_id' => 36, 'name' => 'Chatkhil'],
            ['district_id' => 36, 'name' => 'Companiganj'],
            ['district_id' => 36, 'name' => 'Hatiya'],
            ['district_id' => 36, 'name' => 'Senbagh'],
            ['district_id' => 36, 'name' => 'Sonaimuri'],
            ['district_id' => 36, 'name' => 'Subarnachar'],
            ['district_id' => 36, 'name' => 'Kabirhat'],
            ['district_id' => 37, 'name' => 'Bagaichhari'],
            ['district_id' => 37, 'name' => 'Barkal'],
            ['district_id' => 37, 'name' => 'Kawkhali (Betbunia)'],
            ['district_id' => 37, 'name' => 'Belaichhari'],
            ['district_id' => 37, 'name' => 'Kaptai'],
            ['district_id' => 37, 'name' => 'Juraichhari'],
            ['district_id' => 37, 'name' => 'Langadu'],
            ['district_id' => 37, 'name' => 'Naniyachar'],
            ['district_id' => 37, 'name' => 'Rajasthali'],
            ['district_id' => 37, 'name' => 'Rangamati Sadar'],
            ['district_id' => 38, 'name' => 'Dhamrai'],
            ['district_id' => 38, 'name' => 'Dohar'],
            ['district_id' => 38, 'name' => 'Keraniganj'],
            ['district_id' => 38, 'name' => 'Nawabganj'],
            ['district_id' => 38, 'name' => 'Savar'],
            ['district_id' => 39, 'name' => 'Alfadanga'],
            ['district_id' => 39, 'name' => 'Bhanga'],
            ['district_id' => 39, 'name' => 'Boalmari'],
            ['district_id' => 39, 'name' => 'Charbhadrasan'],
            ['district_id' => 39, 'name' => 'Faridpur Sadar'],
            ['district_id' => 39, 'name' => 'Madhukhali'],
            ['district_id' => 39, 'name' => 'Nagarkanda'],
            ['district_id' => 39, 'name' => 'Sadarpur'],
            ['district_id' => 39, 'name' => 'Saltha'],
            ['district_id' => 40, 'name' => 'Gazipur Sadar'],
            ['district_id' => 40, 'name' => 'Kaliakair'],
            ['district_id' => 40, 'name' => 'Kaliganj'],
            ['district_id' => 40, 'name' => 'Kapasia'],
            ['district_id' => 40, 'name' => 'Sreepur'],
            ['district_id' => 41, 'name' => 'Gopalganj Sadar'],
            ['district_id' => 41, 'name' => 'Kashiani'],
            ['district_id' => 41, 'name' => 'Kotalipara'],
            ['district_id' => 41, 'name' => 'Muksudpur'],
            ['district_id' => 41, 'name' => 'Tungipara'],
            ['district_id' => 42, 'name' => 'Austagram'],
            ['district_id' => 42, 'name' => 'Bajitpur'],
            ['district_id' => 42, 'name' => 'Bhairab'],
            ['district_id' => 42, 'name' => 'Hossainpur'],
            ['district_id' => 42, 'name' => 'Itna'],
            ['district_id' => 42, 'name' => 'Karimganj'],
            ['district_id' => 42, 'name' => 'Katiadi'],
            ['district_id' => 42, 'name' => 'Kishoreganj Sadar'],
            ['district_id' => 42, 'name' => 'Kuliarchar'],
            ['district_id' => 42, 'name' => 'Mithamain'],
            ['district_id' => 42, 'name' => 'Nikli'],
            ['district_id' => 42, 'name' => 'Pakundia'],
            ['district_id' => 42, 'name' => 'Tarail'],
            ['district_id' => 43, 'name' => 'Rajoir'],
            ['district_id' => 43, 'name' => 'Madaripur Sadar'],
            ['district_id' => 43, 'name' => 'Kalkini'],
            ['district_id' => 43, 'name' => 'Shibchar'],
            ['district_id' => 43, 'name' => 'Dasar'],
            ['district_id' => 44, 'name' => 'Daulatpur'],
            ['district_id' => 44, 'name' => 'Ghior'],
            ['district_id' => 44, 'name' => 'Harirampur'],
            ['district_id' => 44, 'name' => 'Manikgonj Sadar'],
            ['district_id' => 44, 'name' => 'Saturia'],
            ['district_id' => 44, 'name' => 'Shivalaya'],
            ['district_id' => 44, 'name' => 'Singair'],
            ['district_id' => 45, 'name' => 'Gazaria'],
            ['district_id' => 45, 'name' => 'Lohajang'],
            ['district_id' => 45, 'name' => 'Munshiganj Sadar'],
            ['district_id' => 45, 'name' => 'Sirajdikhan'],
            ['district_id' => 45, 'name' => 'Sreenagar'],
            ['district_id' => 45, 'name' => 'Tongibari'],
            ['district_id' => 46, 'name' => 'Araihazar'],
            ['district_id' => 46, 'name' => 'Bandar'],
            ['district_id' => 46, 'name' => 'Narayanganj Sadar'],
            ['district_id' => 46, 'name' => 'Rupganj'],
            ['district_id' => 46, 'name' => 'Sonargaon'],
            ['district_id' => 47, 'name' => 'Narsingdi Sadar'],
            ['district_id' => 47, 'name' => 'Belabo'],
            ['district_id' => 47, 'name' => 'Monohardi'],
            ['district_id' => 47, 'name' => 'Palash'],
            ['district_id' => 47, 'name' => 'Raipura'],
            ['district_id' => 47, 'name' => 'Shibpur'],
            ['district_id' => 48, 'name' => 'Baliakandi'],
            ['district_id' => 48, 'name' => 'Goalandaghat'],
            ['district_id' => 48, 'name' => 'Pangsha'],
            ['district_id' => 48, 'name' => 'Rajbari Sadar'],
            ['district_id' => 48, 'name' => 'Kalukhali'],
            ['district_id' => 49, 'name' => 'Bhedarganj'],
            ['district_id' => 49, 'name' => 'Damudya'],
            ['district_id' => 49, 'name' => 'Gosairhat'],
            ['district_id' => 49, 'name' => 'Naria'],
            ['district_id' => 49, 'name' => 'Shariatpur Sadar'],
            ['district_id' => 49, 'name' => 'Zajira'],
            ['district_id' => 50, 'name' => 'Gopalpur'],
            ['district_id' => 50, 'name' => 'Basail'],
            ['district_id' => 50, 'name' => 'Bhuapur'],
            ['district_id' => 50, 'name' => 'Delduar'],
            ['district_id' => 50, 'name' => 'Ghatail'],
            ['district_id' => 50, 'name' => 'Kalihati'],
            ['district_id' => 50, 'name' => 'Madhupur'],
            ['district_id' => 50, 'name' => 'Mirzapur'],
            ['district_id' => 50, 'name' => 'Nagarpur'],
            ['district_id' => 50, 'name' => 'Sakhipur'],
            ['district_id' => 50, 'name' => 'Dhanbari'],
            ['district_id' => 50, 'name' => 'Tangail Sadar'],
            ['district_id' => 51, 'name' => 'Bagerhat Sadar'],
            ['district_id' => 51, 'name' => 'Chitalmari'],
            ['district_id' => 51, 'name' => 'Fakirhat'],
            ['district_id' => 51, 'name' => 'Kachua'],
            ['district_id' => 51, 'name' => 'Mollahat'],
            ['district_id' => 51, 'name' => 'Mongla'],
            ['district_id' => 51, 'name' => 'Morrelganj'],
            ['district_id' => 51, 'name' => 'Rampal'],
            ['district_id' => 51, 'name' => 'Sarankhola'],
            ['district_id' => 52, 'name' => 'Alamdanga'],
            ['district_id' => 52, 'name' => 'Chuadanga Sadar'],
            ['district_id' => 52, 'name' => 'Damurhuda'],
            ['district_id' => 52, 'name' => 'Jibannagar'],
            ['district_id' => 53, 'name' => 'Abhaynagar'],
            ['district_id' => 53, 'name' => 'Bagherpara'],
            ['district_id' => 53, 'name' => 'Chaugachha'],
            ['district_id' => 53, 'name' => 'Jhikargachha'],
            ['district_id' => 53, 'name' => 'Keshabpur'],
            ['district_id' => 53, 'name' => 'Jashore Sadar'],
            ['district_id' => 53, 'name' => 'Manirampur'],
            ['district_id' => 53, 'name' => 'Sharsha'],
            ['district_id' => 54, 'name' => 'Harinakunda'],
            ['district_id' => 54, 'name' => 'Jhenaidah Sadar'],
            ['district_id' => 54, 'name' => 'Kaliganj'],
            ['district_id' => 54, 'name' => 'Kotchandpur'],
            ['district_id' => 54, 'name' => 'Maheshpur'],
            ['district_id' => 54, 'name' => 'Shailkupa'],
            ['district_id' => 55, 'name' => 'Batiaghata'],
            ['district_id' => 55, 'name' => 'Dacope'],
            ['district_id' => 55, 'name' => 'Dumuria'],
            ['district_id' => 55, 'name' => 'Dighalia'],
            ['district_id' => 55, 'name' => 'Koyra'],
            ['district_id' => 55, 'name' => 'Paikgachha'],
            ['district_id' => 55, 'name' => 'Phultala'],
            ['district_id' => 55, 'name' => 'Rupsha'],
            ['district_id' => 55, 'name' => 'Terokhada'],
            ['district_id' => 56, 'name' => 'Bheramara'],
            ['district_id' => 56, 'name' => 'Daulatpur'],
            ['district_id' => 56, 'name' => 'Khoksa'],
            ['district_id' => 56, 'name' => 'Kumarkhali'],
            ['district_id' => 56, 'name' => 'Kushtia Sadar'],
            ['district_id' => 56, 'name' => 'Mirpur'],
            ['district_id' => 57, 'name' => 'Magura Sadar'],
            ['district_id' => 57, 'name' => 'Mohammadpur'],
            ['district_id' => 57, 'name' => 'Shalikha'],
            ['district_id' => 57, 'name' => 'Sreepur'],
            ['district_id' => 58, 'name' => 'Gangni'],
            ['district_id' => 58, 'name' => 'Meherpur Sadar'],
            ['district_id' => 58, 'name' => 'Mujibnagar'],
            ['district_id' => 59, 'name' => 'Kalia'],
            ['district_id' => 59, 'name' => 'Lohagara'],
            ['district_id' => 59, 'name' => 'Narail Sadar'],
            ['district_id' => 60, 'name' => 'Assasuni'],
            ['district_id' => 60, 'name' => 'Debhata'],
            ['district_id' => 60, 'name' => 'Kalaroa'],
            ['district_id' => 60, 'name' => 'Kaliganj'],
            ['district_id' => 60, 'name' => 'Satkhira Sadar'],
            ['district_id' => 60, 'name' => 'Shyamnagar'],
            ['district_id' => 60, 'name' => 'Tala'],
            ['district_id' => 61, 'name' => 'Ajmiriganj'],
            ['district_id' => 61, 'name' => 'Bahubal'],
            ['district_id' => 61, 'name' => 'Baniyachong'],
            ['district_id' => 61, 'name' => 'Chunarughat'],
            ['district_id' => 61, 'name' => 'Habiganj Sadar'],
            ['district_id' => 61, 'name' => 'Lakhai'],
            ['district_id' => 61, 'name' => 'Madhabpur'],
            ['district_id' => 61, 'name' => 'Nabiganj'],
            ['district_id' => 61, 'name' => 'Shayestaganj'],
            ['district_id' => 62, 'name' => 'Barlekha'],
            ['district_id' => 62, 'name' => 'Juri'],
            ['district_id' => 62, 'name' => 'Kamalganj'],
            ['district_id' => 62, 'name' => 'Kulaura'],
            ['district_id' => 62, 'name' => 'Moulvibazar Sadar'],
            ['district_id' => 62, 'name' => 'Rajnagar'],
            ['district_id' => 62, 'name' => 'Sreemangal'],
            ['district_id' => 63, 'name' => 'Bishwamvarpur'],
            ['district_id' => 63, 'name' => 'Chhatak'],
            ['district_id' => 63, 'name' => 'Shantiganj'],
            ['district_id' => 63, 'name' => 'Derai'],
            ['district_id' => 63, 'name' => 'Dharamapasha'],
            ['district_id' => 63, 'name' => 'Dowarabazar'],
            ['district_id' => 63, 'name' => 'Jagannathpur'],
            ['district_id' => 63, 'name' => 'Jamalganj'],
            ['district_id' => 63, 'name' => 'Sullah'],
            ['district_id' => 63, 'name' => 'Sunamganj Sadar'],
            ['district_id' => 63, 'name' => 'Tahirpur'],
            ['district_id' => 63, 'name' => 'Madhyanagar'],
            ['district_id' => 64, 'name' => 'Balaganj'],
            ['district_id' => 64, 'name' => 'Beanibazar'],
            ['district_id' => 64, 'name' => 'Bishwanath'],
            ['district_id' => 64, 'name' => 'Companiganj'],
            ['district_id' => 64, 'name' => 'Dakshin Surma'],
            ['district_id' => 64, 'name' => 'Fenchuganj'],
            ['district_id' => 64, 'name' => 'Golapganj'],
            ['district_id' => 64, 'name' => 'Gowainghat'],
            ['district_id' => 64, 'name' => 'Jaintiapur'],
            ['district_id' => 64, 'name' => 'Kanaighat'],
            ['district_id' => 64, 'name' => 'Osmani Nagar'],
            ['district_id' => 64, 'name' => 'Sylhet Sadar'],
            ['district_id' => 64, 'name' => 'Zakiganj'],
        ];

        foreach ($thana as $key => $value) {
            Thana::create($value);
        }
    }
}
